defaultPortal: hubspot-sandbox
portals:
  - name: hubspot-sandbox
    portalId: 14557846
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CNmGgrymLxIIAA0ADAAA4AEYlsX4BiCyt_cIKO7pDDIZAE2iOiU9W00M_0XfXxRVJ6KwuO8htyAfuDooAAAEQQAAAHgAAAAAAAAAAIABAAAAAAAEwADAB2D-_zEAAAAAAAAAYEIZAE2iOiUQtCXWnE1YvUVgCfI5J-aIudSXJkoDbmEx
        expiresAt: '2021-07-02T13:55:13.375Z'
    personalAccessKey: >-
      CiRiNzRlNTcyNi1kNzUxLTQ2NmQtYWNjMS1hMzYyZWQwMzUyNzIQlsX4Bhiyt_cIKhkABeaRgskt5MgW3AB2lN7G2P5uaWIEWEk4SgNuYTE
